version: "3"
services:

  db:
    image: postgres:12.16
    env_file:
      - .env

    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/db.sql
      - ./pg_data:/var/lib/postgresql/data/
    ports:
      - '5431:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  
  app:
    build: .
    env_file:
      - .env-server
    tty: true
    
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code/
    ports:
      - '8000:8000'
    depends_on:

      db:
        condition: service_healthy 
        
volumes:
  pg_data:


